<a href="https://colab.research.google.com/github/Redwoods/Py/blob/master/numpy/numpy_1_intro_R.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## python module 1. numpy



---



#### 라이브러리를 import 시키는 방법 4가지

**파이썬 코드에서 라이브러리를 import 시키는 방식**은 아래와 같이 4가지로 나눌 수 있다.



1.   라이브러리의 이름을 바로 import하는 방식
         예) import numpy
         이렇게 import를 하면 해당 라이브러리의 풀네임을 이용하여 필요한 API를 호출할 수 있음
         
2.   라이브러리의 별명을 지정하는 방식
         예) import numpy as np
         가장 일반적인 방식임
         a = np,array()
3.   from을 이용하는 방식

         from을 이용하면 해당 API의 이름을 쓰지 않고 API를 바로 쓸 수 있다는 장점이 있음
         from numpy import array, arange
         a = array()
         an = arange(10)

         
4.   필요한 라이브러리에 모든 API를 사용
         예) from numpy import *
            이 경우에도 from을 사용하여 직접 필요한 API를 기술함





##### 첫 번째 방식 - 라이브러리의 이름을 바로 import하는 방식

In [1]:
# 1. 라이브러리의 이름을 바로 import하는 방식

import numpy

a1 = numpy.array([1,2])

print("a1 = ", a1, ", type = ", type(a1))

('a1 = ', array([1, 2]), ', type = ', <type 'numpy.ndarray'>)


##### 두 번째 방식 - 라이브러리의 별명을 지정하는 방식

In [2]:
# 2. 라이브러리의 별명을 지정하는 방식

import numpy as np

a2 = np.array([1,2])

print("a2 = ", a2, ", type = ", type(a2))

('a2 = ', array([1, 2]), ', type = ', <type 'numpy.ndarray'>)


예) numpy라는 라이브러리를 as 다음에 나오는 np로 지정

##### 세 번째 방식 - from을 이용하는 방식

In [3]:
# 3. from을 이용하는 방식

from numpy import array

a3 = array([1, 2])

print("a3 = ", a3, ", type = ", type(a3))

('a3 = ', array([1, 2]), ', type = ', <type 'numpy.ndarray'>)


numpy 라이브러리에 속해있는 array API를 위의 첫 번째 및 두 번째 예에서처럼 numpy.array 또는 np.array 라고 하지 않고, 바로 array를 사용

> => 즉, numpy.array가 아닌 array로 바로 사용 가능



##### 네 번째 방식 - 필요한 라이브러리에 모든 API를 사용

In [4]:
# 4. 필요한 라이브러리에 모든 API를 사용

from numpy import *

result = exp(1) + log(1.7) + sqrt(2)

print("result = ", result, ", type = ", type(result))

('result = ', 4.663123641894311, ', type = ', <type 'numpy.float64'>)


In [5]:
a4 = array(range(1,5)).reshape(2,2)

print("a4 = ", a4, ", type = ", type(a4))

('a4 = ', array([[1, 2],
       [3, 4]]), ', type = ', <type 'numpy.ndarray'>)


### numpy array의 속성

In [6]:
# shape of numpy arrays
a1.shape, a2.shape, a3.shape, a4.shape

((2,), (2,), (2,), (2, 2))

In [7]:
# dimension of numpy arrays
a1.ndim, a2.ndim, a3.ndim, a4.ndim

(1, 1, 1, 2)

In [8]:
# size of numpy arrays
a1.size, a2.size, a3.size, a4.size

(2, 2, 2, 4)

In [9]:
# dtype of numpy arrays
a1.dtype, a2.dtype, a3.dtype, a4.dtype

(dtype('int64'), dtype('int64'), dtype('int64'), dtype('int64'))

In [11]:
# reshape의 또 다른 사용 방법 
a4r = array(range(1,5)).reshape(-1,2)
a4r
a4r.shape, a4r.ndim, a4r.size, a4r.dtype

((2, 2), 2, 4, dtype('int64'))

### numpy

numpy의 개념과 numpy가 필요한 이유, numpy를 이용하여 벡터와 matrix 즉, 행렬을 만들고 이를 상호변환 시킬 수 있는 API를 사용하는 방법에 대해 알아본다.

#### numpy의 개념, 그리고 numpy를 사용하는 이유

- **numpy**

    * numpy는 머신러닝 코드 개발을 할 경우 자주 사용되는 벡터, 행렬 등을 표현하고 연산할 때 반드시 필요한 라이브러리다.  
    * 벡터와 행렬을 이용하면 수치계산이 매우 빨리 수행된다.
    * 벡터, 2차원행렬 등을 일반화 => 배열 또는 텐서(tensor)



- numpy array vs. list

    *  머신러닝에서 숫자, 사람, 동물 등의 인식을 하기 위해서는 이미지 데이터를 행렬(matrix)로 변환하는 것이 중요하다.
    *  행렬을 나타내기 위해서는 list를 사용할 수도 있지만, 행렬 연산이 직관적이지 않고 오류 가능성이 높기 때문에 **행렬 연산을 위해서는 numpy 사용이 필수적**이다.



## 행렬연산 I

- 요소별로 연산
- elementwise operation

In [ ]:
# 행렬연산


# A = (1 0)    B = (1 1)
#     (0 1)        (1 1)

# 각 요소의 인덱스에 맞춰서, 즉 원소별로  연산이 수행된다.
# A + B = (2 1)
#         (1 2)

In [12]:
import numpy as np # 라이브러리의 별명을 지정하는 방식을 사용

In [13]:
# 리스트로 행렬을 표현하면,

A = [ [1,0], [0,1] ]
B = [ [1,1], [1,1] ]

A + B   # 행렬 연산이 아닌 리스트 연산으로 리스트가 확장된다.

[[1, 0], [0, 1], [1, 1], [1, 1]]

=> 리스트 연산이 됨

In [14]:
# numpy matrix, 직관적임

A = np.array([ [1,0], [0,1] ])
B = np.array([ [1,1], [1,1] ])

A + B  # 행렬 연산

array([[2, 1],
       [1, 2]])

In [15]:
# A,B
print(A)
print(B)

[[1 0]
 [0 1]]
[[1 1]
 [1 1]]


=>  numpy로 행렬 선언 및 연산을 하였기 때문에 행렬 연산의 결과가 나옴

### numpy vector(1차원 배열)

#### 벡터 생성

- **벡터(vector) 생성**


> 벡터는 np.array([...])를 사용하여 생성한다.

        예) import numpy as np

> 머신러닝 코드 구현 시, 연산을 위해서 벡터, matrix 등의 구조(shape), 차원(dimension)을 확인하는 것이 필요하다.




In [16]:
A = np.array([1,2,3])
B = np.array([4,5,6])

# vector A, B 출력
print("A = ", A, ", B = ", B)

# vector A, B 구조 출력 => shape
print("A.shape = {0}, B.shape =  {1}".format(A.shape, B.shape))

# vector A, B 차원 출력 => ndim
print("A.ndim = {0}, B.ndim = {1}".format(A.ndim, B.ndim))

('A = ', array([1, 2, 3]), ', B = ', array([4, 5, 6]))
A.shape = (3,), B.shape =  (3,)
A.ndim = 1, B.ndim = 1


##### A, B는 항목(즉 요소)가 세개인 벡터임.

> [행벡터](https://terms.naver.com/entry.nhn?docId=3338356&cid=47324&categoryId=47324) vs. [열벡터](https://terms.naver.com/entry.nhn?docId=3338418&ref=y&cid=47324&categoryId=47324)  
>> 그러면 일반 벡터인 A, B를 열벡터 또는 행벡터로 변경하는 방법은?

In [17]:
A.shape, B.shape  # , B는 항목(즉 요소)가 세개인 벡터

((3,), (3,))

#### 열벡터로 변환

In [18]:
A[:, np.newaxis]   # 열벡터

array([[1],
       [2],
       [3]])

In [19]:
A,A[:,np.newaxis]

(array([1, 2, 3]), array([[1],
        [2],
        [3]]))

In [23]:
A1  = A[:, np.newaxis]
A.shape, A.ndim, A1.shape, A1.ndim

((3,), 1, (3, 1), 2)

#### 행벡터로 변환

In [25]:
B, B.shape,B.ndim

(array([4, 5, 6]), (3,), 1)

In [26]:
B[np.newaxis,:]   # 행벡터

array([[4, 5, 6]])

In [28]:
B1  = B[np.newaxis,:]
B1.shape, B1.ndim

((1, 3), 2)

In [29]:
print(A,B)
A1,B1

(array([1, 2, 3]), array([4, 5, 6]))


(array([[1],
        [2],
        [3]]), array([[4, 5, 6]]))

In [30]:
A.shape, B.shape, A1.shape, B1.shape

((3,), (3,), (3, 1), (1, 3))

### [확인]

In [32]:
# A, B, A1, B1의 차원을 비교해보시오.
A.ndim,B.ndim,A1.ndim,B1.ndim

(1, 1, 2, 2)

> **reshape()**를 이용해서 벡터의 형태 변형도 가능하다.
- A.reshape(3,1)
- A.reshape(1,3)

### [도전] reshape를 이용해서 벡터 A를 열벡터, 행벡터로 변환하시오.

In [35]:
# reshape를 이용해서 벡터 A를 열벡터, 행벡터로 변환
A2c=A.reshape(3,1)  # 열벡터, column vector
A2r=A.reshape(1,3)  # 행벡터, row vector
A, A2c, A2r

(array([1, 2, 3]), array([[1],
        [2],
        [3]]), array([[1, 2, 3]]))

In [36]:
A.ndim,A2c.ndim,A2r.ndim

(1, 2, 2)



---



## 벡터 산술연산

- **벡터 산술연산**


> 벡터 간 산술연산 (+, -, x, /, %)는 벡터의 각각의 원소에 대해서 행해진다.



In [37]:
A,B

(array([1, 2, 3]), array([4, 5, 6]))

In [46]:
# vector 산술 연산 (elementwise operation)
# 벡터는 1차원 배열!
# A = np.array([1,2,3])
# B = np.array([4,5,6])

print("A+B = ", A+B)
print("A-B = ", A-B)
print("A*B = ", A*B)
print("A/B = ", A/B)
print("A%B = ", A%B)
print("A**B", A**B)

('A+B = ', array([5, 7, 9]))
('A-B = ', array([-3, -3, -3]))
('A*B = ', array([ 4, 10, 18]))
('A/B = ', array([0, 0, 0]))
('A%B = ', array([1, 2, 3]))
('A**B', array([  1,  32, 729]))


In [44]:
B%A

array([0, 1, 0])

In [45]:
A**B

array([  1,  32, 729])

### numpy array, matrix (2차원 배열, 행렬)

#### 행렬 생성

- **행렬 생성**


> matrix는 벡터와 마찬가지로 np.array([ [...], [...], ... ])를 사용하여 생성한다.


>     예)  import numpy as np


          A = (1 2 3)       B = (-1 -2 -3)
              (4 5 6)           (-4 -5 -6)
            shape 2x3       shape 2x3




In [47]:
A = np.array([ [1,2,3], [4,5,6] ])
B = np.array([ [-1,-2,-3], [-4,-5,-6] ])

# vector A, B 구조 출력 => shape
print("A.shape = {0}, B.shape =  {1}".format(A.shape, B.shape))

# vector A, B 차원 출력 => ndim
print("A.ndim = {0}, B.ndim = {1}".format(A.ndim, B.ndim))

A.shape = (2, 3), B.shape =  (2, 3)
A.ndim = 2, B.ndim = 2


#### 형 변환 (reshape)

- **형 변환 (reshape)**


> 벡터를 matrix로 변경하거나 matrix를 다른 구조의 matrix로 변경하기 위해서는 reshape() 사용하여 행렬의 shape를 변경하여야 한다.

           예) D = (1 2 3)   D.reshape(3,2) = (1 2)
                   (4 5 6)                    (3 4)
                                              (5 6)
                shape 2x3             shape 3x2

In [48]:
# reshape()를 이용한 열벡터 생성

C = np.array([1,2,3])  # 기본 벡터

# 벡터 C의 구조 출력 => shape
print("C.shape = ", C.shape)

# 벡터를 (3,1) 행렬로 형 변환 => 열벡터로 변환
C1 = C.reshape(3,1)

print("C1.shape = ", C1.shape)

# 벡터를 (1,3) 행렬로 형 변환 => 행벡터로 변환
C2 = C.reshape(1,3)

print("C2.shape = ", C2.shape)

('C.shape = ', (3,))
('C1.shape = ', (3, 1))
('C2.shape = ', (1, 3))


In [50]:
C.ndim,C1.ndim, C2.ndim

(1, 2, 2)

### 2차원 배열의 구조 변환 (reshape 함수 이용)

In [51]:
# reshape()를 이용한 구조 변경

D = np.array([ [1,2,3], [4,5,6] ])  # (2,3) 배열

# 배열 D의 구조 출력 => shape
print("D.shape = ", D.shape)

# 배열 D를 (3,2) 행렬로 형 변환 
D1 = D.reshape(3,2)

print("D1.shape = ", D1.shape)

# D와 D1 출력
print(D)
print(D1)

('D.shape = ', (2, 3))
('D1.shape = ', (3, 2))
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [52]:
# 전치행렬과 비교 => 다르다!
DT = D.T
D, D1, DT

(array([[1, 2, 3],
        [4, 5, 6]]), array([[1, 2],
        [3, 4],
        [5, 6]]), array([[1, 4],
        [2, 5],
        [3, 6]]))